# Generated by Django 3.0.14 on 2022-08-29 21:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('claim', '0013_claimserviceitem_claimserviceservice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claimserviceservice',
            name='claimlinkedService',
            field=models.ForeignKey(db_column='claimlinkedService', on_delete=django.db.models.deletion.DO_NOTHING, related_name='claimlinkedService', to='claim.ClaimService'),
        ),
    ]
