# Generated by Django 3.2.18 on 2023-04-04 14:11

from django.db import migrations

class Migration(migrations.Migration):

    dependencies = [
        ("claim", "0014_change_code_limit"),
    ]

    operations = [
    ]
