# Generated by Django 3.2.18 on 2023-04-04 14:11

from django.db import migrations
from core.utils import insert_role_right_for_system


def forwards_func(apps, schema_editor):
    RoleRight = apps.get_model("core", "RoleRight")
    Role = apps.get_model("core", "Role")

    # Delete enrollment officer right to interact with claim data
    # Enrollment officer is predefined system role with id 1
    eo_roles = Role.objects.filter(is_system=1, validity_to__isnull=True)
    # Prohibited Roles ID are gql_query_claims_perms (111001)
    # and gql_mutation_deliver_claim_feedback_perms (111009)
    rights_id = [111001, 111009]
    for right_id in rights_id:
        RoleRight.objects.filter(
            role__in=eo_roles, right_id=right_id, validity_to__isnull=True
        ).delete()


def reverse_func(apps, schema_editor):
    Role = apps.get_model("core", "Role")
    eo_roles = Role.objects.filter(is_system=1, validity_to__isnull=True)
    rights_id = [111001, 111009]
    for eo_role in rights_id:
        for right_id in eo_roles:
            insert_role_right_for_system(eo_role.id, right_id, apps)


class Migration(migrations.Migration):

    dependencies = [
        ("claim", "0014_change_code_limit"),
    ]

    operations = [
        migrations.RunPython(forwards_func, reverse_func),
    ]
