# Generated by Django 3.2.16 on 2024-07-24 13:55

from django.db import migrations

from core.utils import insert_role_right_for_system, remove_role_right_for_system

CLAIM_UPDATE_RIGHT = 111013
ADMIN_ROLE = 64
CLAIM_ADMIN_ROLE = 256
ROLES_TO_UPDATE = [
    ADMIN_ROLE,
    CLAIM_ADMIN_ROLE,
]


def add_claim_update_right(apps, schema_editor):
    """
    Add claim update right to the IMIS Administrator and the Claim Administrator.
    """
    for role in ROLES_TO_UPDATE:
        insert_role_right_for_system(role, CLAIM_UPDATE_RIGHT)


def remove_claim_update_right(apps, schema_editor):
    """
    Remove claim update right to the IMIS Administrator and the Claim Administrator.
    """
    for role in ROLES_TO_UPDATE:
        remove_role_right_for_system(role, CLAIM_UPDATE_RIGHT)

class Migration(migrations.Migration):

    dependencies = [
        ('claim', '0020_nhia_claim_details_report_rights'),
    ]

    operations = [
        migrations.RunPython(add_claim_update_right, remove_claim_update_right),
    ]
