# Generated by Django 4.2.27 on 2025-12-15 11:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0034_remove_user_legacy_id_remove_user_validity_from_and_more"),
        ("claim", "0035_merge_20241004_1020"),
    ]

    operations = [
        migrations.AlterField(
            model_name="claim",
            name="admin",
            field=models.ForeignKey(
                blank=True,
                db_column="ClaimAdminId",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="core.claimadmin",
            ),
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.DeleteModel(
                    name="ClaimAdmin",
                ),
            ],
            database_operations=[
                # Intentionally empty — no changes to the database
            ],
        ),
    ]
