# Generated by Django 3.2.17 on 2026-02-10 09:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('claim', '0035_merge_20241004_1020'),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='program',
            field=models.ForeignKey(db_column='program', blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='claim_program', to='program.program'),
        )
    ]
