# Generated by Django 4.2.24 on 2025-10-27 13:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_alter_mutationlog_client_mutation_id'),
        ('claim', '0035_merge_20241004_1020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claim',
            name='admin',
            field=models.ForeignKey(blank=True, db_column='ClaimAdminId', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.claimadmin'),
        ),
        migrations.DeleteModel(
            name='ClaimAdmin',
        ),
    ]
