# Generated by Django 4.2.25 on 2025-11-20 08:01

import core.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('claim', '0036_alter_claim_admin_delete_claimadmin'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReturnedClaim',
            fields=[
                ('id', models.AutoField(db_column='ReturnedClaimID', primary_key=True, serialize=False)),
                ('returned_date', core.fields.DateTimeField(db_column='ReturnedDate')),
                ('audit_user_id', models.IntegerField(db_column='AuditUserID')),
                ('reason', models.TextField(db_column='Reason')),
                ('return_type', models.CharField(db_column='ReturnType', max_length=1)),
                ('claim', models.ForeignKey(db_column='ClaimID', on_delete=django.db.models.deletion.DO_NOTHING, related_name='return_reason', to='claim.claim')),
            ],
            options={
                'db_table': 'tblReturnedClaim',
                'managed': True,
            },
        ),
    ]
