# Generated by Django 4.2.25 on 2025-11-20 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claim', '0037_returnedclaim'),
    ]

    operations = [
        migrations.AddField(
            model_name='returnedclaim',
            name='predefined_reason',
            field=models.TextField(db_column='PredefinedReason', default='a'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='returnedclaim',
            name='reason',
            field=models.TextField(blank=True, db_column='Reason', null=True),
        ),
    ]
