# Generated by Django 4.2.25 on 2025-11-20 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claim', '0038_returnedclaim_predefined_reason_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='returnedclaim',
            name='return_type',
            field=models.IntegerField(db_column='ReturnType'),
        ),
    ]
