# Generated by Django 4.2.25 on 2025-11-26 07:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('claim', '0039_alter_returnedclaim_return_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='claimservice',
            name='availability',
            field=models.BooleanField(db_column='availability', default=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='claimitem',
            name='availability',
            field=models.BooleanField(db_column='availability'),
        ),
    ]
